version: 0.4.{build}-{branch}
branches:
  except:
    - gh-pages
skip_tags: true
cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
platform: Any CPU
configuration: Release
