version: '1.0.{build}'
assembly_info:
  patch: true
  file: MyVersion.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-rc1'
  assembly_version: $(appveyor_build_version)
